# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190228_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
