# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-07 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190307_2118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('passenger', 'flight')]),
        ),
    ]
